"use client";
import { ColorModeScript } from "@chakra-ui/react";
import "./globals.css";
import { Providers, theme } from "./providers";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers> {children}</Providers>
        <ColorModeScript initialColorMode={"light"} />
      </body>
    </html>
  );
}
